[build]
  command = "npm run build"
  functions = "app/functions"
  publish = "app/dist"

[dev]
  targetPort = 5173
  framework = "vite"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
